yapt/shelf/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
		url(r'^$', 'shelf.views.home'),
		url(r'^addArticle/$', 'shelf.views.addArticle'),
		url(r'^home/$', 'shelf.views.home'),
		url(r'^search/$', 'shelf.views.search', {'filter_name' : 'all'}),
		url(r'^search/([a-zA-z0-9]+)$', 'shelf.views.search', name='search'),
		url(r'^editArticle/(\d+)/$', 'shelf.views.edit_article', name='edit'),
)

yapt/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
		(r'^', include('shelf.urls')),
)

yapt/shelf/models.py
from django.db import models
from datetime import date, timedelta

# Duration
class Duration(models.Model):
	name = models.CharField(max_length=100, unique=True)
	numberDays = models.PositiveIntegerField(null=True, blank=True)
	date = models.DateField(null=True, blank=True)

	def getEndDate(self):
		today = date.today()
		if self.numberDays is None:
			if self.date is None:
				raise ValueError('Date or NumberDays must have a value')
			else:
				return date(today.year, self.date.month, self.date.day)	
		else:
			return today + timedelta(self.numberDays);
			
	def __unicode__(self):
		return self.name

# Article
class Article(models.Model):
	title = models.CharField(max_length=200)
	url = models.URLField(max_length=200, unique=True)
	creationDate = models.DateTimeField(auto_now_add=True, auto_now=False, editable=False)
	endDate = models.DateField(null=True)
	hasBeenRead = models.BooleanField(default=False)

	def __unicode__(self):
		return self.title

yapt/shelf/forms.py
#-*- coding: utf-8 -*-
from django import forms
from shelf.models import Article, Duration
from shelf.articleFilters import *
from django.forms import extras
from django.forms.util import flatatt
import datetime

class ArticleForm(forms.ModelForm):
	duration = forms.ModelChoiceField(queryset=Duration.objects.all(), required=False)

	class Meta:
		model = Article
		fields = ['url', 'title', 'duration']

class SelectEditArticleForm(forms.Form):
	articles = forms.ModelChoiceField(queryset=Article.objects.all().extra(select={'lower_title':'lower(title)'}).order_by('lower_title'))	

class EditArticleForm(forms.ModelForm):
	id = forms.CharField(widget=forms.HiddenInput)

	def __init__(self, *args, **kwargs):
		super(EditArticleForm, self).__init__(*args, **kwargs)
		self.fields['hasBeenRead'].label = "Has been read"
		self.fields['endDate'].label = "End date"
		self.fields['endDate'].required = False
	
	def clean(self):
		cleaned_data = super(EditArticleForm, self).clean()
		article_id = cleaned_data['id']
		try:
			article = Article.objects.get(id=int(article_id))
			endDate = self.cleaned_data['endDate']
			cleaned_data['creationDate'] = article.creationDate
			if ((article.endDate is not None and endDate != article.endDate) or (article.endDate is None)) and endDate is not None and endDate < datetime.date.today():
				self._errors["endDate"] = self.error_class([u"End date cannot be in the past."])					
		except Article.DoesNotExist:
			raise forms.ValidationError(u"Article does not exist.")					

		return cleaned_data

	class Meta:
		model = Article

class DurationAdminForm(forms.ModelForm):
	class Meta:
		model = Duration

	def clean(self):
		cleaned_data = super(DurationAdminForm, self).clean()
		numberDays = cleaned_data.get('numberDays')
		date = cleaned_data.get('date')
		if numberDays is None and date is None:
			raise forms.ValidationError("NumberDays and Date cannot be both empty.")
		return cleaned_data

class SearchForm(forms.Form):
	filterChoices = (ArticleFilters.items())
	filter = forms.ChoiceField(choices=filterChoices)
	urlTitle = forms.CharField(max_length=400, label='Url/Title', required=False)
	paging = forms.CharField(widget=forms.HiddenInput, required=False)

	def clean_filter(self):
		filter_name = self.cleaned_data['filter']
		if filter_name is None:
			raise forms.ValidationError("Filter has not a valid value.")

		if not ArticleFilters.contains(filter_name):
			raise forms.ValidationError("Filter has not a valid value.")

		return filter_name

yapt/shelf/views.py
#-*- coding: utf-8 -*-

from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.db.models import Count, Q
from shelf.forms import ArticleForm, SearchForm, EditArticleForm, SelectEditArticleForm
from shelf.models import Article, Duration
from shelf.articleFilters import *
from datetime import date, timedelta
import math
from django.conf import settings

def home(request):
	if request.method == 'POST':
		if 'delete' in request.POST:
			delete_article(request.POST['delete'])
		elif 'read' in request.POST:
			read_article(request.POST['read'])

	today = date.today()
	number_overrdue_articles = Article.objects.filter(endDate__lt=today, hasBeenRead=False).count()
	articles = Article.objects\
		.filter(endDate__gte=today, hasBeenRead=False)\
		.extra(select={'lower_title':'lower(title)'})\
		.order_by('endDate', 'lower_title')[:settings.HOMEPAGE_TOP_ITEMS]

	overdue_filter_name = OverdueArticlesFilter.name()
	return render(request, 'home.html', locals())

def search(request, filter_name):	
	page_size = settings.SEARCHPAGE_PAGING_SIZE

	if request.method == 'GET':		
		if filter_name is None:
			raise ValueError('filter_name cannot be None.')

		page = 0
		url_title = None
	else:
		form = SearchForm(request.POST)
		if form.is_valid():
			page = int(form.cleaned_data['paging'])
						
			if 'delete' in request.POST:
				delete_article(request.POST['delete'])
			elif 'read' in request.POST:
				read_article(request.POST['read'])
			elif 'next' in request.POST:
				page += 1				
			elif 'previous' in request.POST:
				page -= 1	

			url_title = form.cleaned_data['urlTitle']
			filter_name = form.cleaned_data['filter']

	page, nb_pages, articles, nb_articles = search_articles(page, page_size, url_title, filter_name)
	postValues = request.POST.copy()
	postValues['paging'] = page
	postValues['filter'] = filter_name
	form = SearchForm(postValues)
			
	return render(request, 'search.html', locals())

def delete_article(article_id):
	Article.objects.filter(id=article_id).delete()

def read_article(article_id):
	Article.objects.filter(id=article_id).update(hasBeenRead=True)	

def search_articles(page, page_size, url_title, filter_name):
	articles = ArticleFilters.get_filter(filter_name).get_articles()
	articles = articles.extra(select={'lower_title':'lower(title)'})
	if url_title is not None and len(url_title.strip()) > 0:
		articles = articles.filter(Q(url__icontains=url_title) | Q(title__icontains=url_title))

	nb_articles = articles.count()
	nb_pages = int(math.ceil(float(nb_articles) / page_size))

	# in case another filter is applied and less records are returned
	if page < 0 or page > nb_pages:
		page = 0

	start_index = page * page_size
	end_index = (page + 1) * page_size
	articles = articles.order_by('endDate', 'lower_title')[start_index:end_index]
	return page, nb_pages, articles, nb_articles

def addArticle(request):
	if request.method == 'POST':
		form = ArticleForm(request.POST)

		if form.is_valid():
			article = form.save(commit=False)
			duration = form.cleaned_data['duration']
			if duration is not None:
				article.endDate = duration.getEndDate()
			article.save()

			messages.success(request, u'The article has been added.')
			form = ArticleForm
	else:
		form = ArticleForm

	return render(request, 'addArticle.html', locals())

def edit_article(request, article_id):
	article = get_object_or_404(Article, id=article_id)		
	if request.method == 'GET':
		form = EditArticleForm(instance = article)
	elif request.method == 'POST':
		form = EditArticleForm(request.POST, instance=article)
		if form.is_valid():
			form.save()
			postValues = request.POST.copy()
			postValues['id'] = article_id
			messages.success(request, u'The article has been updated.')
	print article.creationDate 
	readOnlyFields = { 'Creation Date': article.creationDate }
	return render(request, 'editArticle.html', locals())

yapt/shelf/templates/addArticle.html
{% extends "base.html" %}

{% block title %}Add article{% endblock %}

{% block navAddArticle %}active{% endblock %}

{% block content %}

<form action="" method="post" class="form-horizontal">
	{% csrf_token %}
	<legend class="dataCmd">
		<span class="title">Add a new article</span>
		<button id="save" name="save" class="btn reset btn-default" title="Add"><i class="icon-ok"></i></button>
	</legend>
{% if messages %}
		<div class="row-fluid">
			<div class="span12 messages text-center">
				{% for message in messages %}
					<span{% if message.tags %} class="text-{{ message.tags }}"{% endif %}>{{ message }}</span>
				{% endfor %}
			</div>
		</div>
		{% endif %}
	<fieldset>
		{% for field in form.visible_fields %}
			{% if forloop.counter0|divisibleby:"2" %}
				<div class="row-fluid"> 
			{% endif %}
				<div class="control-group {% if not forloop.counter0|divisibleby:'2' %} right-panel {% endif %}{% if field.errors %} error {% endif %}">
					<div class="span2"><label class="control-label" for="id_{{ field.html_name }}">{{ field.label }}</label></div>
					<div class="controls span4">
						{{ field }}
						{% if field.errors %}
							{% for error in field.errors %}
								<span class="help-inline error">{{ error }}</span>
							{% endfor %}
						{% endif %}
					</div>
				</div>
			{% if not forloop.counter0|divisibleby:"2" or forloop.last%}
				</div> 
			{% endif %}
		{% endfor %}
		
		{% for field in form.hidden_fields %}
			{{ field }}
		{% endfor %}
	</fieldset>
</form>
{% endblock %}

yapt/shelf/templates/base.html
{% load static %}

{% load url from future %}
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>
			Shelf - {% block title %}{% endblock %}
		</title>
		<link rel="stylesheet" href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="{% static 'style.css'%}" media="screen" />
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
	</head>		
	<body>
		<div class="container-fluid main">			
			<div class="masthead">
        <div class="navbar">
          <div class="navbar-inner">
            <div class="container">
              <ul class="nav">
								<li><h4 class="muted" title="v0.5">Shelf</h4></li>
                <li class="{% block navHome %} {% endblock %}"><a href="{% url 'shelf.views.home' %}">Home</a></li>
                <li class="{% block navAddArticle %} {% endblock %}"><a href="{% url 'shelf.views.addArticle' %}">Add</a></li>
                <li class="{% block navSearch %} {% endblock %}"><a href="{% url 'shelf.views.search' %}">Search</a></li>
                {% block fakePages %}{% endblock %}
              </ul>
						</div>
          </div>
	{% block subNav %}{% endblock %}
        </div><!-- /.navbar -->

      </div> <!-- /.masthead -->

			<div class="container-fluid sub">			
				{% block content %}				{% endblock %}
				</form>
			</div>
		</div>
	</body>
</html>

yapt/shelf/templates/editArticle.html
{% extends "base.html" %}

{% block title %}Edit article{% endblock %}
{% block fakePages %}<li class="block fake-page-nav-item">Edit</li>{% endblock %}

{% block content %}

<script type="text/javascript">
	$(function(){
		date = $("#id_endDate").val();
		$("#id_endDate").datepicker();
	});
</script>

	<form action="" method="post" class="form-horizontal">
		{% csrf_token %}
		<legend class="dataCmd">
			<span class="title">Edit</span>
			<button id="save" name="save" title="Save" class="btn reset btn-default"><i class="icon-ok"></i></button>
		</legend>
		{% if messages %}
		<div class="row-fluid">
			<div class="span12 messages text-center">
				{% for message in messages %}
					<span{% if message.tags %} class="text-{{ message.tags }}"{% endif %}>{{ message }}</span>
				{% endfor %}
			</div>
		</div>
		{% endif %}
		<fieldset>
			{% for field in form.visible_fields %}
				{% if forloop.counter0|divisibleby:"2" %}
					<div class="row-fluid"> 
				{% endif %}
					<div class="control-group {% if not forloop.counter0|divisibleby:'2' %} right-panel {% endif %}{% if field.errors %} error {% endif %}">
						<div class="span2"><label class="control-label" for="id_{{ field.html_name }}">{{ field.label }}</label></div>
						<div class="controls span4">
							{{ field }}
							{% if field.errors %}
								{% for error in field.errors %}
									<span class="help-inline error">{{ error }}</span>
								{% endfor %}
							{% endif %}
						</div>
					</div>
				{% if not forloop.counter0|divisibleby:"2" or forloop.last%}
					</div> 
				{% endif %}
			{% endfor %}	
			
			{% for key,value in readOnlyFields.items %}
				{% if forloop.counter0|divisibleby:"2" %}
					<div class="row-fluid"> 
				{% endif %}				
					<div class="control-group {% if not forloop.counter0|divisibleby:'2' %} right-panel {% endif %}">
						<div class="span2"><label class="control-label" for="id_{{ key }}">{{ key }}</label></div>
						<div class="controls span4 readonly">
							{{ value|date:"d M Y" }}
						</div>
					</div>
				{% if not forloop.counter0|divisibleby:"2" or forloop.last%}
					</div> 
				{% endif %}
			{% endfor %}

			{% for field in form.hidden_fields %}
	      {{ field }}
			{% endfor %}		
		</fieldset>
	</form>
{% endblock %}

yapt/shelf/templates/home.html
{% extends "base.html" %}
{% load shelf_filters %}

{% block title %}Home{% endblock %}

{% block navHome %}active{% endblock %}

{% block content %}
			<form action="" method="post"> {% csrf_token %}
				<div class="row-fluid">	
					<div class="span12">
						<legend>Reading list</legend>												
					</div>
				</div>
				{% if number_overrdue_articles > 0 %}
					<div class="row-fluid">			
						<div class="span12 text-center">
							<h5>
								<a href="{% url search overdue_filter_name %}" class="text-warning">{{ number_overrdue_articles }} article{{number_overrdue_articles|pluralize}} {% if number_overrdue_articles == 1 %} is {% else %} are {% endif %} overdue.</a>
							</h5>
						</div>
					</div>
				{% endif %}
				{% for article in articles %}	
					{% ifchanged article.endDate|get_reading_date_string %}					
						<div class="row-fluid">			
							<div class="span12"><h5>{{ article.endDate|get_reading_date_string }}</h5></div>						
						</div>
	 				{% endifchanged %}
					<div class="row-fluid">			
						<div class="span4 wrap">
							<a href="{{ article.url }}" target="_blank" title="Due on {{ article.endDate }}"">{{ article.title }}</a>
						</div>
						<div class="span4"></div>
						<div class="span3"></div>
						<div class="span1">
							<button value="{{ article.id }}" type="submit" name="delete" class="reset" title="Delete" onclick="return confirm('Do you want to delete the article \'{{ article.title }}\'?')"><i class="icon-trash"></i></button>
							<a href="{% url edit article.id %}" title="Edit"><i class=" icon-edit"></i></a>
							<button value="{{ article.id }}" type="submit" name="read" class="reset" title="Read" onclick="return confirm('Have you read the article \'{{ article.title }}\'?')"><i class="icon-ok"></i></button>
						</div>
					</div>	
					{% empty %}
					<div class="row-fluid">			
						<div class="span12">No planned readings.</div>
					</div>
				{% endfor %}					
			</form>
{% endblock %}

yapt/shelf/templates/search.html
{% extends "base.html" %}

{% block title %}Search{% endblock %}

{% block navSearch %}active{% endblock %}

{% comment %} {% block subNav %}<ul class="subNav"><li><a>Search</a></li><li><a>Schedule</a></li></ul>{% endblock %} {% endcomment %}

{% block content %}
<form action="" method="post" class="form-horizontal">
	{% csrf_token %}
	
	<legend class="dataCmd">
		<span class="title">Search</span>
		<button id="search" name="search" title="Search" class="btn reset btn-default"><i class="icon-search"></i></button>
	</legend>

	<fieldset>
		<div class="row-fluid">			
			<div class="control-group">
				<div class="span2"><label class="control-label" for="id_{{ form.urlTitle.html_name }}">{{ form.urlTitle.label }}</label></div>
				<div class="controls span5">
					{{ form.urlTitle }}
				</div>
				<div class="span2"><label class="control-label rightPanel" for="id_{{ form.filter.html_name }}">{{ form.filter.label }}</label></div>
				<div class="controls span3">
					{{ form.filter }}
				</div>
		</div>		
	</fieldset>

		<div class="row-fluid">			
			<legend>Items</legend>
		</div>
		{{ form.paging }}
		{% if articles %}
			<div class="row-fluid">		
				<div class="span4 wrap"><b>Title</b></div>
				<div class="span4"></div>
				<div class="span3"><b>Duration</b></div>
				<div class="span1"><b>Action</b></div>
			</div>
			{% for article in articles %}	
				<div class="row-fluid">			
					<div class="span4 wrap">
						<a href="{{ article.url }}" target="_blank">{{ article.title }}</a>
					</div>
					<div class="span4"></div>
					<div class="span3">{{ article.endDate }}</div>
					<div class="span1">
						<button value="{{ article.id }}" type="submit" name="delete" class="reset" title="Delete" onclick="return confirm('Do you want to delete the article \'{{ article.title }}\'?')"><i class="icon-trash"></i></button>
						<a href="{% url edit article.id %}" title="Edit"><i class="icon-edit"></i></a>
						{% if article.endDate %}
							<button value="{{ article.id }}" type="submit" name="read" class="btn reset {% if article.hasBeenRead %} disabled {% endif %}" title="Read" onclick="return confirm('Have you read the article \'{{ article.title }}\'?')" {% if article.hasBeenRead %} disabled {% endif %}><i class="icon-ok"></i></button>
						{% endif %}
					</div>
				</div>								
			{% endfor %}
			<!-- Paging -->
			<div class="row-fluid">
				<div class="text-center span12">
					{% if page > 0 %}
						<button type="submit" name="previous" class="btn reset" title="Previous"><i class="icon-chevron-left"></i></button>
					{% endif %}					
					Page {{ page|add:1 }} of {{ nb_pages }} ({{ nb_articles }} item{{ nb_articles|pluralize }}).
					{% if page < nb_pages|add:-1 %}
						<button type="submit" name="next" class="btn reset" title="Next"><i class="icon-chevron-right"></i></button>
					{% endif %}
					</div>
			</div>		
		{% else %}
			<div class="row-fluid">			
				<div class="span12">No items found. Please update your search criteria.</div>
			</div>
		{% endif %}

</form>
{% endblock %}